[build-system]
requires = ["setuptools>=61", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "viam-wrap"
dependencies = [
  "viam-sdk>=0.15.0",
]
dynamic = ["version"]

[project.scripts]
viam-wrap = "viam_wrap:main"

[tool.setuptools_scm]
