on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py_version }}
    - name: install
      run: pip install ruff
    - name: check
      run: ruff check
