on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - py_version: "3.9"
          ruff_version: "py39"
        - py_version: "3.10"
          ruff_version: "py310"
        - py_version: "3.11"
          ruff_version: "py311"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py_version }}
    - name: install
      run: pip install ruff pylint
    - name: check
      run: ruff check --target-version ${{ matrix.ruff_version }}
    - name: compileall
      run: python -m compileall -f *.py examples/
    - name: pylint
      run: pylint --errors-only viam_wrap.py
