on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: install
      run: pip install ruff
    - name: check
      run: ruff check
